import BigTitleQuotePictureSection from "../../components/layout/BigTitleQuotePictureSection";
import Page from "../../components/layout/Page";
import TitleIconSection from "../../components/layout/TitleIconSection";
import plists from "../../data/plists";
import projects from "../../data/projects";
import SmallCard from "../../components/atoms/SmallCard";
import SpotifyPlayer from "../../components/media/SpotifyPlayer";

export default function PlaylistAssistantPage() {
    const playlistAssistantProject = projects.find(
        (project) => project.title === "AI Playlist Assistant"
    );
    return (
        <Page>
            <BigTitleQuotePictureSection
                title={playlistAssistantProject.title}
                icon={playlistAssistantProject.icon}
                subtitle={playlistAssistantProject.subtitle}
                quote={playlistAssistantProject.pageBlurb}
                image={playlistAssistantProject.thumbnail}
                imageAlt={playlistAssistantProject.title + " thumbnail"}
            >
            </BigTitleQuotePictureSection>
            <TitleIconSection title="Example Output" iconName="spotify">
                <p>
                    The following playlists had their artwork and description generated by the AI. The playlists themselves were created by me.
                </p>
                <div className="grid grid-cols-1 3xl:grid-cols-2 gap-4">
                    {plists.map((plist, index) => {
                        return (
                            <SmallCard key={index}>
                                <div className="flex flex-col lg:flex-row items-center"  >
                                    <img src={plist.coverArt} alt={plist.name} className="lg:max-w-sm md:max-w-md sm:max-w-lg p-4" />
                                    <div className="flex flex-col gap-4 p-4">
                                        <h3 className="text-xl">{plist.name}</h3>
                                        <p className="text-sm subtle-text">{plist.description}</p>
                                        <SpotifyPlayer id={plist.id} type="playlist" title={plist.name} className="w-full" />
                                    </div>
                                </div>
                            </SmallCard>
                        )

                    }

                    )}
                </div>
            </TitleIconSection>
        </Page>
    )
}