import { useState } from "react";
import IconButton from "../../components/atoms/IconButton";
import BigTitleQuotePictureSection from "../../components/layout/BigTitleQuotePictureSection";
import Page from "../../components/layout/Page";
import TitleIconSection from "../../components/layout/TitleIconSection";
import plists from "../../data/plists";
import projects from "../../data/projects";
import { motion } from "framer-motion";
import SmallCard from "../../components/atoms/SmallCard";
export default function PlaylistAssistantPage() {
    const playlistAssistantProject = projects.find(
        (project) => project.title === "AI Playlist Assistant"
    );
    return (
        <Page>
            <BigTitleQuotePictureSection
                title={playlistAssistantProject.title}
                icon={playlistAssistantProject.icon}
                subtitle={playlistAssistantProject.subtitle}
                quote={playlistAssistantProject.pageBlurb}
                image={playlistAssistantProject.thumbnail}
                imageAlt={playlistAssistantProject.title + " thumbnail"}
            >
            </BigTitleQuotePictureSection>
            <TitleIconSection title="Example Output" iconName="spotify">
                <p>
                    The following playlists had their artwork and description generated by the AI. The playlists themselves were created by me.
                </p>
                <div className="grid grid-cols-1 3xl:grid-cols-2 gap-4">
                    {plists.map((plist, index) => {
                        return (
                            <SmallCard>
                                <div className="flex flex-col lg:flex-row items-center"  >
                                    <img src={plist.coverArt} alt={plist.name} className="lg:max-w-sm md:max-w-md sm:max-w-lg p-4" />
                                    <div className="flex flex-col gap-4 p-4">
                                        <h3 className="text-xl">{plist.name}</h3>
                                        <p className="text-sm subtle-text">{plist.description}</p>
                                        <SpotifyPlaylistPlayer playlistId={plist.id} />
                                    </div>
                                </div>
                            </SmallCard>
                        )

                    }

                    )}
                </div>
            </TitleIconSection>
        </Page>
    )
}

function SpotifyPlaylistPlayer({ playlistId }) {
    const SMALL_HEIGHT = 152;
    const LARGE_HEIGHT = 352;
    const [height, setHeight] = useState(SMALL_HEIGHT);

    const toggleSize = () => {
        setHeight(height === SMALL_HEIGHT ? LARGE_HEIGHT : SMALL_HEIGHT);
    };

    return (
        <div className="w-full flex-col space-y-4">
            <motion.iframe
                title={playlistId}
                src={`https://open.spotify.com/embed/playlist/${playlistId}?utm_source=generator`}
                className="max-w-screen-sm"
                width="100%"
                height={height}
                animate={{ height: height }}
                transition={{ duration: 0.3, ease: "easeInOut" }}
                allowFullScreen=""
                allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                loading="lazy"
            />
            <IconButton
                icon={height === SMALL_HEIGHT ? "maximize" : "minimize"}
                text={height === SMALL_HEIGHT ? "Expand" : "Shrink"}
                className="bg-spotify-green w-fit rounded-md"
                onClick={toggleSize}
            />
        </div>
    );
}
