import BigTitleQuotePictureSection from "../../components/layout/BigTitleQuotePictureSection";
import Page from "../../components/layout/Page";
import TitleIconSection from "../../components/layout/TitleIconSection";
import projects from "../../data/projects";
export default function PlaylistAssistantPage() {
    const playlistAssistantProject = projects.find(
        (project) => project.title === "AI Playlist Assistant"
    );
    return (
        <Page>
            <BigTitleQuotePictureSection
                title={playlistAssistantProject.title}
                icon={playlistAssistantProject.icon}
                subtitle={playlistAssistantProject.subtitle}
                quote={playlistAssistantProject.pageBlurb}
                image={playlistAssistantProject.thumbnail}
                imageAlt={playlistAssistantProject.title + " thumbnail"}
            >
            </BigTitleQuotePictureSection>
            <TitleIconSection title="Example Output" iconName="spotify">
                <p>
                    The following playlists had their artwork and description generated by the AI. The playlists themselves were created by me.
                </p>
                <div className="grid xl:grid-cols-2 gap-4">
                    <SpotifyPlaylist playlistId="3Q7YAcZW1YEtK4yRVroWPj" />
                    <SpotifyPlaylist playlistId="5kYWsnVUcrcNmnb0zDtPmP" />
                    <SpotifyPlaylist playlistId="35I4u8E4We9S899ygin3dZ" />
                    <SpotifyPlaylist playlistId="4c5B4uCN9Wh428Nxfh6RmS" />
                </div>

            </TitleIconSection>
        </Page>
    )
}

function SpotifyPlaylist({ playlistId }) {
    return (
        <iframe className="" src={`https://open.spotify.com/embed/playlist/${playlistId}?utm_source=generator`} width="100%" height="152" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
    )
}