name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to the branch you want to deploy from
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # This is needed for the deployment action to work

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        # No need to set base path here since it's in vite.config.js

      - name: Copy Data Files
        run: |
          mkdir -p dist/data
          cp -r src/data/* dist/data/
          ls -la dist/data # Verify the files were copied correctly

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
