name: Prettier Code Formatter

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Format Code
        run: npx prettier --write .

      - name: Check Code Format
        run: npx prettier --check .
